In [6]:
import numpy as np

In [11]:
a=np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [52]:
b=np.array([[1,2,3,4],[4,5,6,10
                      ]])
print(b)

[[ 1  2  3  4]
 [ 4  5  6 10]]


In [5]:
a.ndim

1

In [8]:
b.ndim   #Get dimension

2

In [9]:
b.shape


(2, 3)

In [12]:
a.dtype


dtype('int16')

In [15]:
a.itemsize #2bytes  

2

In [16]:
a.size #total size

3

In [17]:
a.nbytes


6

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
a[1,5]


13

In [21]:
a[1,-2]

13

In [41]:
a[0:2,1:5]

array([[ 2,  3,  4,  5],
       [ 9, 10, 11, 12]])

In [36]:
a[:,2]

array([ 3, 10])

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones((2,5),dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [49]:
np.full((2,2),99,dtype='float')

array([[99., 99.],
       [99., 99.]])

In [54]:
np.full_like(b,4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [55]:
np.random.rand(4,2)

array([[0.30161096, 0.48195415],
       [0.13811992, 0.14371309],
       [0.50952306, 0.81506127],
       [0.28470777, 0.82799015]])

In [60]:
np.random.randint(1,10,size=(3,3))

array([[5, 9, 3],
       [2, 1, 3],
       [1, 2, 4]])

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [65]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100

print(a)
print(b)

[1 2 3]
[100   2   3]


In [68]:
a=np.array([0,1,2,3])
a+2

array([2, 3, 4, 5])

In [69]:
a=np.array([0,1,2,3])
print(a/0)

[nan inf inf inf]


C:\Users\jagan\AppData\Local\Temp/ipykernel_15388/36499159.py:2: RuntimeWarning: divide by zero encountered in true_divide
  print(a/0)
C:\Users\jagan\AppData\Local\Temp/ipykernel_15388/36499159.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(a/0)


In [70]:
a=np.array([0,1,2,3])
print(a/1)

[0. 1. 2. 3.]


In [71]:
a ** 5

array([  0,   1,  32, 243], dtype=int32)

In [72]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])